services:
  onlyoffice-ds:
    container_name: onlyoffice-ds
    image: onlyoffice/documentserver:latest
    restart: always
    envronment:
      - JWT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
      - LANG=en_us.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_us.utf-8
    volumes:
      - ../fonts:/usr/share/fonts/truetype/custom
      - ../dictionaries/he_IL:/var/www/onlyoffice/documentserver/server/FileConverter/bin/spellchecker/dictionaries/hr_IL:ro
      - ./run.sh:/run_custom.sh
      - /srv/logs/onlyoffice:/var/log/onlyoffice
    ports:
      - "8080:80"
    entrypoint: "/run_custom.sh"
    deploy:
      resources:
        limits:
          memory: 2G